/*
 * Signature Evolution - API Documentation
 * Signature Evolution - API Documentation
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bdo.evolution_native.client.model.addcard;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

/**
 * BankAcctIdType
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Generated
public class BankAcctIdType {
    @JsonProperty("acctType")
    private String acctType = null;

    @JsonProperty("acctId")
    private String acctId = null;

    @JsonProperty("acctIdMasked")
    private String acctIdMasked = null;

}
