/*
 * Signature Evolution - API Documentation
 * Signature Evolution - API Documentation
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bdo.evolution_native.client.model.addcard;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

/**
 * CardAcctRecType
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Generated
public class CardAcctRecType {
    @JsonProperty("cardAcctInfo")
    private CardAcctInfoType cardAcctInfo = null;

    @JsonProperty("shortName")
    private String shortName = null;

}
