/*
 * Signature Evolution - API Documentation
 * Signature Evolution - API Documentation
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bdo.evolution_native.client.model.addcard;

import com.bdo.evolution_native.client.model.StatusType;
import com.bdo.evolution_native.client.model.initiatemodel.RqUID;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

/**
 * CardAcctAddRs
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Generated
public class CardAcctAddRs {
    @JsonProperty("rqUID")
    private RqUID rqUID = null;

    @JsonProperty("status")
    private StatusType status = null;

    @JsonProperty("custId")
    private CustIdType custId = null;

    @JsonProperty("cardAcctRec")
    private CardAcctRecType cardAcctRec = null;

}
