/*
 * Party Reference Customer Profile Retrieve API
 * The party reference data directory service domain maintains a potentially wide range of party reference data that might be used in any interaction between the bank and the party including relationship development, sales/marketing, servicing and product delivery. This can include general reference and contact details, party associations, demographic details and some servicing preferences. Different information may be maintained for different party types such as individuals, corporates, partners
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bdo.evolution_native.model.retrivemodel;

import com.bdo.evolution_native.model.Links;
import com.bdo.evolution_native.model.Meta;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

/**
 * RetrieveCustomerResponse
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Generated
public class RetrieveCustomerResponse {
    @JsonProperty("Data")
    private RetrieveCustomerResponseData data;

    @JsonProperty("Links")
    private Links links;

    @JsonProperty("Meta")
    private Meta meta;
  
}
