/*
 * Add on card information attached to account.
 * The Card Account Information API is used to access cards information and transactions.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bdo.evolution_native.model.addcard;

import com.bdo.evolution_native.constants.EvolutionConstantUtils;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import javax.validation.Valid;
import javax.validation.constraints.Digits;

/**
 * AccountLinks
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Generated
@Valid
public class AccountLinks {
    @JsonProperty("BankAccountIdType")
    private @Valid  BankAccountIdType bankAccountIdType;

    @JsonProperty("SequenceId")
    @Digits(integer = 2, fraction = 0, message = EvolutionConstantUtils.SEQUENCEID_SIZE_VALIDATION)
    private Integer sequenceId;

}
