/*
 * Add on card information attached to account.
 * The Card Account Information API is used to access cards information and transactions.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bdo.evolution_native.model.addcard;

import com.bdo.evolution_native.constants.EvolutionConstantUtils;
import com.bdo.evolution_native.enums.AccountType;
import com.bdo.evolution_native.util.ValueOfEnum;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import javax.validation.Valid;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * BankAccountIdType
 */

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Generated
@Valid
public class BankAccountIdType {
    @JsonProperty("AccountType")
    @Size(max = 2, message = EvolutionConstantUtils.ACCOUNT_TYPE_SIZE_MESSAGE)
    @ValueOfEnum(enumClass = AccountType.class, message = EvolutionConstantUtils.ACCOUNT_TYPE_FORMAT_MESSAGE_ADDCARD)
    private String accountType;

    @JsonProperty("AccountId")
    @Pattern(regexp = "^-?\\d{1,12}$", message = EvolutionConstantUtils.BANK_ACCOUNT_ID_CARD_SIZE_MESSAGE)
    private String accountId;

    @JsonProperty("AccountIdMasked")
    private String accountIdMasked;

}
