EVOLUTION:
  RETRY:
    MAX_ATTEMPT: 3
    MIN-INTERVAL-IN-MILLIS: 700
  BASE_URL: ${ICBS_EVOLUTION_URL}
  ACCOUNT:
    BALANCE_INQUIRY:
      PATH: ${EVOLUTION_ACCOUNT_BALANCE_INQUIRY_PATH}
    EMPLOYEE_INITIATE:
      PATH: ${EVOLUTION_EMPLOYEE_INITIATE_PATH}
    CUSTOMER_ACCOUNT_INITIATE:
      PATH: ${CUSTOMER_ACCOUNT_INITIATE_PATH}
  CUSTOMER:
    LIST:
      PATH: ${EVOLUTION_CUSTOMER_LIST_PATH}
    INITIATE:
      PATH: ${EVOLUTION_CUSTOMER_INITIATE_PATH}
    Retrieve:
      PATH:${EVOLUTION_CUSTOMER_Retrieve_PATH}
  CARD:
    ADD_CARD:
      PATH:${EVOLUTION_CARD_ADD_CARD_PATH}
  TOKEN:
    PATH: ${ICBS_EVOLUTION_TOKEN_PATH}
    CHANNEL_ID_HEADER: ${ICBS_EVOLUTION_CHANNEL_ID_HEADER}
    SOURCE_HEADER: ${ICBS_EVOLUTION_SOURCE_HEADER}

info:
  app:
    description: '@project.description@'
    name: '@project.artifactId@'
    version: '@project.version@'

logging:
  level:
    com:
      bdo:
        evolution_native: ERROR
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
server:
  error:
    whitelabel:
      enabled: false
  port: 8095
  servlet:
    context-path: /ms-evolution-native
spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    static-path-pattern: /swagger*
    throw-exception-if-no-handler-found: true

# enabled endpoints for health and info
management:
  info:
    env:
      enabled: true
  endpoints:
    loggers:
      enabled: true
    web:
      exposure:
        include: "health,info,loggers"
    health:
      group:
        custom:
          show-components: always
          show-details: always
    jmx:
      exposure:
        include: "health,info"
